# Site
name: 'Learning Dock'
description: 'Learing Dock'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: '/Learning_Dock'
disqus: ''
email: 'shiba.dog.leo.private@gmail.com'
mailchimp-list: ''

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-asciidoc

asciidoctor:
  attributes:
  - stem

authors:
    shiba:
      name:           shiba dog
      site:           
      avatar:         /assets/images/avatar.jpg
      bio:            ""
      email:          shiba.dog.leo.private@gmail.com
      twitter:        https://twitter.com/shiba_dog_leo

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: shiba
      avatar: /assets/images/avatar.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      

  - scope:
      path: "_Blog"
    values:
      layout: post
      author: shiba
      avatar: /assets/images/avatar.jpg
      draft: true

# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]